### ISSUE TITLE
Include more planetary bodies.

### ISSUE THREAD

**Issue by Mohamed-Ayaan358** [acmpesuecc/3D-Portfolio#1]
### What do we want you to do?

The website currently only utilises the earth and moon models, this issue explores looking into adding more bodies as well as other phenomena.

### Possible solutions

Utilise the inbuilt objects of three.js and obtain the wrapping images from the net, This will require a more in-depth knowledge of the module.

### Previous knowledge

The main problem you will face as I did is that the orbiting and placement of the objects could be finicky.

#### 1. Open Access time: 
 [1 hour] if each block time has passed

#### 2. Block time: 
[1.5 hours], to show significant progress.

**Comment by sukruthi-s** [comment]
CAN I BE ASSIGNED THIS (SUKRUTHI SANAMPUDI PES2UG21CS472)

**Comment by SarthakSKumar** [comment]
I wish to work on this issue. Please assign.
Thanks in advance!

**Comment by Vaarun-Kamath** [comment]
hey can i work on this pls :)
